### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by Daniel-Mietchen** [beoutbreakprepared/nCoV2019#19]
to clarify reusability. Probably best to do it separately for code and data.

**Comment by aezarebski** [comment]
Good idea! @Mougk @beoutbreakprepared the following might be useful https://choosealicense.com/

**Comment by SandeepAswathnarayana** [comment]
@beoutbreakprepared @aezarebski @Daniel-Mietchen Great initiative with the synthesis of information/data!

Considering the project motive and permissions allowed, I believe the GNU GPLv3 would fit the project's community. Glad to hear inputs or other suggestions.
https://choosealicense.com/licenses/gpl-3.0/

**Comment by Mougk** [comment]
@aezarebski: my suggestion would be https://choosealicense.com/licenses/mit/

**Comment by aezarebski** [comment]
@Mougk I think it would be better to choose one of the GNU ones or the Apache one because they require that any changes be documented. I'd prefer that any changes people make to the data that is being published have to be documented. The only hard constraint is that we are not liable for correctness which I think they all provide.

**Comment by Mougk** [comment]
Sounds good to me.. let’s go with gnu 

Moritz.

**Comment by aezarebski** [comment]
Minor update on this, after reading the license section of the linked manuscript, it may be better to choose a data specific license

https://arxiv.org/abs/2002.11626

**Comment by Mougk** [comment]
LICENSE has now been added.
