### ISSUE TITLE
Implausible time periods need cleaning

### ISSUE THREAD

**Issue by beoutbreakprepared** [beoutbreakprepared/nCoV2019#3]
Motivation:Need to develop code cleaning scripts to identify poor quality timestamp data

Idea: identify IDs where dates are not in format DD.MM.YYYY or DD.MM.YYYY-DD.MM.YYYY
Flag IDs where ordering of timestamps is implausible given timeline e.g. time of onset being after time of death
Flag IDs where date is in the future and therefore impossible

**Comment by aezarebski** [comment]
Yep, this seems like an important one. There are already quite a few things appearing as dates.

I might suggest that we adopt the format of `dd.mm.yyyy` for a known date, `dd.mm.yyyy-dd.mm.yyyy` for a closed interval and `-dd.mm.yyyy` and `dd.mm.yyyy-` for one sided intervals (since there are several entries with the "pre" suffix.

**Comment by beoutbreakprepared** [comment]
Yup that sounds like a good way of dealing with "pre-"s

**Comment by aezarebski** [comment]
I've put in a PR implementing this in a checker tool. If that gets merged we can close this.
